### ISSUE TITLE
Nav bar shows white dots after hovering over items (macOS Chrome)

### ISSUE THREAD

**Issue by cqrmskgiub** [RosieSews/masksnow#117]
# Bug report

**What is the current behavior?**
After hovering over navbar items (when white rounded corners show up), white dots appear around border of white rounded corners, mostly on top, sometimes on side.

**If the current behavior is a bug, please provide the steps to reproduce.**
Hover over the navbar items.

**What is the expected behavior?**
No white dots.

**Other relevant information:**
macOS Mojave Chrome v80.0.3987.163 64-bit
![image](https://user-images.githubusercontent.com/29091366/79672912-ce9bac00-818a-11ea-886d-5f46eaf81ada.png)

Node.js version: 
NPM/Yarn version
Operating System: 
Additional tools:

**Comment by gvan12** [comment]
I see this too though I have no idea what's causing it. They may just go away if I we convert them all to be MUI button-links.

**Comment by cqrmskgiub** [comment]
No problem. It's not a big deal, but figured I'd throw it in here for a 'maybe someday figure it out' issue :)

**Comment by alfdocimo** [comment]
Hi! I believe this is caused by the css property `border-radius`

I could suggest two approaches that I've tried locally and seem to work:

1) Adding an `overflow: hidden;` property to the Narbar Menu

reference: https://stackoverflow.com/questions/16938437/white-corner-showing-on-black-box-with-border-radius

2) On components that make use of border-radius for the navbar like `src\components\StyledElements\MoreDots.js` & `src\components\StyledElements\NavItem.js`. I believe if we set that from 5% to 0 and this could go away. Plus, it would look more consistent with the overall design (or is it just me? 😇)

With these changes, it's working fine for me on Chrome 81.0.4044.113 for Windows that is. Can anyone test this on a Mac? I can raise a PR with this

![5021e43d3482e7738906947bc319566a](https://user-images.githubusercontent.com/22222078/80155513-22125d80-85c2-11ea-9073-17c0ff696613.gif)
